---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: minhanh-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:/lamlng/Fedora_Rawhide/home:lamlng.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - micro
      - starship
      - ibus-bamboo
      - tailscale
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.brave.Browser
        - org.gnome.Loupe
        - com.getpostman.Postman
        - com.github.marhkb.Pods
        - com.slack.Slack
        - org.filezillaproject.Filezilla
        - app.devsuite.Ptyxis
        - io.missioncenter.MissionCenter
        - it.mijorus.gearlever
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages
  
  - type: brew
    brew-analytics: false # disable telemetry

  - type: script
    scripts:
      - mdatp.sh
      - expressvpn.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

